create table films (
    id bigint generated by default as identity,
    name varchar(100) not null,
    description varchar(255) not null,
    types varchar(11) not null,
    style varchar(30) not null,
    date_release date not null,
    primary key (id)
);